### ISSUE TITLE
Problema registrazione

### ISSUE THREAD

**Issue by luca-zanchetta** [luca-zanchetta/Tesina-NewInfostud#1]
Per @Orioncode0
--------------------
Problema concettuale nella registrazione: uno studente dovrebbe essere iscritto ad un corso di laurea, così come un docente dovrebbe avere un corso assegnatogli. Inoltre, sia uno studente che un docente dovrebbero avere una matricola assegnata.
L'ho pensata così, dimmi (quando puoi) se può essere una soluzione: in fase di registrazione, chiediamo soltanto i dati personali sia dello studente che del docente (per segreteria e amministrazione il problema non si pone per fortuna), generando dinamicamente una matricola ad iscrizione avvenuta. Ammettiamo uno stato intermedio in cui uno studente registrato non è iscritto ad alcun corso di laurea (id 0 se preferisci), così come un docente può non avere ancora alcun corso assegnato per l'insegnamento (anche in quel caso id 0). Ha senso come cosa?

**Comment by Mattia-Aquilina** [comment]
La proposta ha senso essendoci delle utenze, quali amministrazione e segreteria, in grado di modificare i dati relativi agli altri utenti. Nascerebbe però il seguente problema: un'utenza che si trova nel suddetto stato intermedio, è in grado di usufruire della piattaforma? In caso positivo è necessario perfezionare il funzionamento del login. Un'altra soluzione consiste nello specificare corso e corso di laurea, dipendentemente dall'utenza in questione, al momento della registrazione; In qualsiasi momento la segreteria sarà in grado di modificare i dati in questione.

**Comment by luca-zanchetta** [comment]
Nel caso di uno studente che non sia iscritto ad alcun corso di laurea, le uniche funzionalità a disposizione potrebbero essere la visualizzazione dei propri dati personali e la possibilità di iscriversi ad un corso di laurea, visto che non avrebbe una carriera all'attivo. Il caso di un docente senza corso assegnato invece potrebbe essere effettivamente improbabile; che senso avrebbe tener traccia di un docente "fantasma"? Volendo possiamo inserire nella form di registrazione dei docenti anche la materia cui fa riferimento... Potremmo farlo anche per lo studente, ma l'idea dello stato intermedio sembrava dare più dinamicità al sito (esistono studenti senza carriere attive, ho approfondito con i neo laureati😄). Fammi sapere cosa ne pensi, e per me questa issue si può chiudere
