### ISSUE TITLE
Possibile nuova feature Login

### ISSUE THREAD

**Issue by luca-zanchetta** [luca-zanchetta/Tesina-NewInfostud#2]
Per @Orioncode0 
Vogliamo implementare una funzione di recupero matricola/username/password se in fase di login l'utente non dovesse ricordare una di queste cose?

**Comment by Mattia-Aquilina** [comment]
Si potrebbe pensare di implementare un semplice script che sovrascriva la password con una stringa generata casualmente, che successivamente viene comunicata all'utente.

**Comment by luca-zanchetta** [comment]
Carina come idea, anche se poco sicura in ambiti diversi da quello "didattico". Se poi l'utente è in grado di modificarla, per me si può fare e si può chiudere la issue
