### ISSUE TITLE
Visualizza corsi di laurea

### ISSUE THREAD

**Issue by luca-zanchetta** [luca-zanchetta/Tesina-NewInfostud#3]
Per @Orioncode0
Ho riscontrato due problemi nella creazione del layout di visualizzazione dei corsi di laurea (vedi visualizzaCorsiDiLaurea.php nella branch "edit-Luca"):
   1) La pagina si rompe quando si effettua il resize, a causa della presenza della barra di ricerca posta in alto;
   2) In che modo vogliamo visualizzare l'elenco dei corsi di laurea disponibili? Vogliamo farlo con i blocchi (stile visualizzazione esami per capirci - in tal caso, inseriamo un colore?), oppure nel modo in cui avevamo pensato di elencare i post delle bacheche?

**Comment by Mattia-Aquilina** [comment]
Ho corretto il problema con l'ultimo commit nella branch 'edit-luca'.
